spring.application.name=gms

spring.config.import=optional:file:config.properties


#   Connect to database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=${DB_DRIVER}

#   JPA Properties
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#   Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

#   JWT Token Configuration
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}

# 1 hour in milliseconds
jwt.accessExpiration=3600000

# 7 days in milliseconds
jwt.refreshExpiration=604800000


#   Configuration port Frontend
port.fe=http://localhost:3000
